omar/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from omar.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('categorie/', include('categorie.urls')),
    path('product/', include('product.urls')),
    path('contact/', include('contact.urls')),
    path('back_office/', include('back_office.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import OrderSummaryView, navShopView, SellerView, order_list, order_create, order_delete, order_detail, \
    order_edit, add_to_cart, add_to_cart_quick, remove_from_cart, remove_single_produit_from_cart, CheckoutView, \
    AddCouponView

app_name = 'product'

urlpatterns = [

    path('liste', views.product_list, name='indexProduit'),
    path('create/', views.product_create, name='createProduit'),
    path('<int:product_id>/', views.product_detail, name='detailProduit'),
    path('detail/<int:product_id>/', views.view_product, name='viewProduit'),
    #path('edit/<int:product_id>/', views.product_edit, name='editProduit'),
    url(r'(?P<id>\d+)/product_edit/$', views.product_edit, name='editProduit'),
    path('delete/<int:product_id>/', views.product_delete, name='deleteProduit'),

    path('order-summary/', OrderSummaryView, name='order-summary'),
    path('shop/<str:slug>/', navShopView, name='shop'),
    path('seller/', SellerView.as_view(), name='seller'),

    # url Order

    path('order', order_list, name='indexOrder'),
    path('order/create/', order_create, name='createOrder'),
    path('order/<int:order_id>/', order_detail, name='detailOrder'),
    path('order/edit/<int:order_id>/', order_edit, name='editOrder'),
    path('order/delete/<int:order_id>/', order_delete, name='deleteOrder'),

    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('add-to-cart-quick/<pk>/', add_to_cart_quick, name='add-to-cart-quick'),

    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-produit-from-cart/<pk>/', remove_single_produit_from_cart,
         name='remove_single_produit_from_cart'),
    path('checkout/', CheckoutView, name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
]

product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from accounts.forms import RegistrationSellerForm
from categorie.models import Categorie
from .forms import CreateProduit, CreateOrder, CheckoutForm, CouponForm
from .models import Produit, Photos, Order, Produit, OrderProduit, Address, Coupon
from . import forms
from django.contrib import messages
from django.forms import formset_factory, modelformset_factory
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import ListView, DetailView, View
from django.core.paginator import Paginator
from django.utils import timezone
import random
import string

from django.core.mail import BadHeaderError, send_mail, EmailMultiAlternatives
from django.template.loader import get_template, render_to_string

# Create your views here.

def product_list(request):
    classe_active = 'produit'
    produits = Produit.objects.all()

    return render(request, "product/product_list.html", locals())


def product_create(request):
    classe_active = 'produit'
    Photoformset = modelformset_factory(Photos, fields=('photo',), extra=4)
    if request.method == 'POST':
        print('test1')
        form = CreateProduit(request.POST or None)
        formset = Photoformset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            print('test2')
            produit = form.save(commit=False)
            produit.code_ref = create_ref_code()
            produit.agent = request.user
            produit.save()
            messages.success(request, "Le produit a été crée avec succès !")
            for f in formset:
                try:
                    photo = Photos(produit=produit, photo=f.cleaned_data['photo'])
                    photo.save()
                except Exception as e:
                    print(e)
                    break
            return redirect('product:indexProduit')




    else:
        form = CreateProduit()
        formset = Photoformset(queryset=Photos.objects.none())
    context = {
        'form': form,
        'formset': formset,
        'classe_active': classe_active,
    }

    return render(request, 'product/product_create.html', context)


def product_detail(request, product_id):
    classe_active = 'produit'
    try:
        # produits = Produit.objects.all()
        produit = Produit.objects.get(pk=product_id)
        # photos = Photos.objects.exclude(photo__isnull=True).exclude(photo__exact='').filter(produit=product_id)
        lesphotos = produit.photos.all()
    except Produit.DoesNotExist:
        raise Http404("Le produit n'existe pas")
    return render(request, 'product/product_detail.html', locals())


def view_product(request, product_id):
    categories = Categorie.objects.all()
    try:
        produit = Produit.objects.get(pk=product_id)
        photos = produit.photos.all()
        classe_active = produit.categorie.nom
    except Produit.DoesNotExist:
        raise Http404("Le produit n'existe pas")
    return render(request, 'product/view_product.html', locals())


def product_edit(request, id):
    classe_active = 'produit'
    produit = get_object_or_404(Produit,id=id)
    Photoformset = modelformset_factory(Photos, fields=('photo',), extra=4, max_num=4)
    classe_active = 3
    if request.method == 'POST':
        form = CreateProduit(request.POST or None, instance=produit)
        formset = Photoformset(request.POST or None, request.FILES or None)
        if form.is_valid() and formset.is_valid():
            form.save()
            messages.success(request, "Le produit a été crée avec succès !")
            data = Photos.objects.filter(produit=produit)

            for index, f in enumerate(formset):
                if f.cleaned_data:
                    if f.cleaned_data['id'] is None:
                        photo = Photos(produit=produit, photo=f.cleaned_data.get('photo'))
                        photo.save()
                    elif f.cleaned_data['photo'] is False:
                        photo=Photos.objects.get(id=request.POST.get('form-' + str(index) + '-id'))
                        photo.delete()
                    else:
                        photo = Photos(produit=produit, photo=f.cleaned_data.get('photo'))
                        d = Photos.objects.get(id=data[index].id)
                        d.photo = photo.photo
                        d.save()



            return redirect('product:indexProduit')


    else:
        form = CreateProduit(instance=produit)
        formset = Photoformset(queryset=Photos.objects.filter(produit=produit))
    context = {
        'form': form,
        'produit': produit,
        'formset': formset,
    }

    return render(request, 'product/product_edit.html', context)


def product_delete(request, product_id):
    classe_active = 'produit'
    produit = Produit.objects.filter(pk=product_id)
    produit.delete()
    messages.success(request, "Le produit a été supprimé avec succès !")
    produits = Produit.objects.all()

    return redirect('product:indexProduit')


# class OrderSummaryView(LoginRequiredMixin, View):
def OrderSummaryView(request):
    try:
        categories = Categorie.objects.all()
        sessionID = request.COOKIES.get('sessionid')
        order = Order.objects.get(sessionID=sessionID, ordered=False)
        if order:
            produits = order.produits.all()
            if produits:
                cat = produits[0].produit.categorie
                classe_active = cat.nom
                interestedProduits = Produit.objects.filter(categorie=cat)[:8]

            else:
                interestedProduits = Produit.objects.all()[:8]

            best_sellers = getBestSellersProducts()
            context = {
                'object': order,
                'interestedProduits': interestedProduits,
                'best_sellers': best_sellers,
                'categories': categories,
                'classe_active': classe_active,
            }
            return render(request, 'product/order_summary.html', context)
        else:
            return redirect(request.META['HTTP_REFERER'])

    except ObjectDoesNotExist:
        messages.warning(request, "You do not have an active order")
        return redirect("/")


def getBestSellersProducts():
    # Here we get product that must selled
    orders = Order.objects.all()[:20]  # TODO Ici faudra filtrer par les mieux vendus

    # after we get related categories and set the list
    produits = []
    if orders:
        for o in orders:
            try:
                orderProduits = o.produits.all()
                print("--------------------------333--------------------------")
                print(orderProduits)
                print("--------------------------333--------------------------")
                if orderProduits:
                    cat = orderProduits[0].produit.categorie
                    tmp = Produit.objects.filter(categorie=cat)[:1]
                    produits.append(tmp)
            except:
                print('::::::::: Exception in getBestSellersProducts:::::::::')

    if len(produits) == 0:
        produits = Produit.objects.all()[:20]

    return produits

def navShopView(request, slug):

    classe_active = slug
    categories = Categorie.objects.all()
    produits = Produit.objects.filter(categorie__nom=slug)
    paginator = Paginator(produits, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'products': produits,
        'classe_active': classe_active,
        'page_obj': page_obj,
        'categories': categories,
    }
    print(produits)
    return render(request, 'product/shop.html', context)


class SellerView(View):
    def get(self, *args, **kwargs):
        form = RegistrationSellerForm()
        context = {
            'form': form
        }
        return render(self.request, "product/seller.html", context)




def order_list(request):
    classe_active = 'order'
    orders = Order.objects.all()
    return render(request, "order/order_list.html", locals())

def order_create(request):
    classe_active = 'order'
    orders = Order.objects.all()
    return render(request, "order/order_create.html", locals())

def order_detail(request, order_id):
    classe_active = 'order'
    try:
        order = Order.objects.get(pk=order_id)
    except Order.DoesNotExist:
        raise Http404("La commande n'existe pas")
    return render(request, 'order/order_detail.html', locals())

def order_edit(request, order_id):
    classe_active = 'order'
    post = get_object_or_404(Order, pk=order_id)
    if request.method == 'POST':
        form = CreateOrder(request.POST, request.FILES, instance=post)
        if form.is_valid():
            # save order to DB # DEBUG: # TODO:
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            messages.success(request, "Le order a été mofifié avec succès !")
            return redirect('order:indexOrder')
    else:
        form = CreateOrder(instance=post)

    return render(request, 'order/order_create.html', {'form': form, 'classe_active': classe_active})

def order_delete(request):
    classe_active = 'order'
    orders = Order.objects.all()
    return render(request, "order/order_list.html", locals())


def add_to_cart(request, pk):
    sessionID = request.COOKIES.get('sessionid')
    produit = get_object_or_404(Produit, pk=pk)
    order_produit, created = OrderProduit.objects.get_or_create(
        produit=produit,
        sessionID=sessionID,
        ordered=False,
        user=request.user
    )
    order_qs = Order.objects.filter(sessionID=sessionID, ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # check if the order produit is in the order

product/templates/order/order_detail.html
{% extends 'admin/base_admin.html' %}
{% block titre %} {{ block.super }} - Commande {% endblock %}

{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}

{% block footer %}
{% include 'admin/footer_admin.html' %}
{% endblock %}
{% block content %}

<div class="container">
<h2 align="center">Detail Commande</h2>
    <div class="row">


            <div class="col-md-5">
                <div  class="tab-content">


                    <!-- Profile Image -->
                    <div class="card card-primary card-outline">
                        <div class="card-body box-profile">


                            <h3 class="profile-username text-center">{{ order.user  }}</h3>

                            <p class="text-muted text-center"></p>

                            <ul class="list-group list-group-unbordered mb-3">
                                <li class="list-group-item">
                                    <b>Utilisateur</b> <a class="float-right">{{ order.user.fullname }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Ref Code</b> <a class="float-right">{{ order.ref_code }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Date de la commande</b> <a class="float-right">{{ order.ordered_date |date:"l d F Y" }} {{ order.ordered_date|time:"H:i" }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Validé</b> <a class="float-right">{% if order.ordered %} Oui {% else %} Non{% endif %}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Adresse d'expedition</b> <a class="float-right">{{ order.shipping_address }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Adresse de facturation</b> <a class="float-right">{{ order.billing_address }}</a>
                                </li>
                                <li class="list-group-item">
                                    <b>Reçu</b> <a class="float-right">{% if order.received %} Oui {% else %} Non{% endif %}</a>
                                </li>
                            </ul>

                            <a href="#" class="btn btn-primary btn-block"><b></b></a>
                            <a href="{% url 'product:editOrder' order.id %}" style="text-decoration: none;" ><i class="fa fa-edit" style="font-size:24px"></i></a>
                            <a href="{% url 'product:deleteOrder' order.id %}" style="text-decoration: none" onclick="return confirm('Voulez-vous vraiment supprimer l''gence {{ order.title }} ?');"><i class="fa fa-trash" style="font-size:24px"></i></a>

                        </div>
                    </div>

                </div>

            </div>

        <div class="col-md-7">
            <div  class="tab-content">


                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">


                        <h3 class="profile-username text-center">Produits</h3>

                        <p class="text-muted text-center"></p>

                        <ul class="list-group list-group-unbordered mb-3">
                            <table>
                                {% for order_item in order.items.all %}
                                <tr>

                                    <td>{{ order_item.item.title }} </td>
                                    <td>{{ order_item.item.price }} </td>
                                    <td>{{ order_item.item.purchase_price }} </td>
                                    <td>{{ order_item.item.sale_price }} </td>
                                    <td>{{ order_item.item.provider }} </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </ul>

                        <a href="#" class="btn btn-primary btn-block"><b></b></a>
                        <a href="{% url 'product:editOrder' order.id %}" style="text-decoration: none;" ><i class="fa fa-edit" style="font-size:24px"></i></a>
                        <a href="{% url 'product:deleteOrder' order.id %}" style="text-decoration: none" onclick="return confirm('Voulez-vous vraiment supprimer l''gence {{ order.title }} ?');"><i class="fa fa-trash" style="font-size:24px"></i></a>

                    </div>
                </div>

             </div>


         </div>




      </div>
</div>







{% endblock %}

product/templates/order/order_list.html
{% extends 'admin/base_admin.html' %}
{% load static %}
{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}

{% block footer %}
{% include 'admin/footer_admin.html' %}
{% endblock %}



{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/dataTables.bootstrap4.min.css' %}"/>
{% endblock %}

{% block content %}
<div class="container py-2">

    <h2 align="center" class="customColor pt-2">Historique des commandes</h2>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{% url 'product:createOrder' %}" class="btn btn-default float-right pl-2"> Ajouter une commande </a><br/>
        </div>
        <div class="card-body">
            <div class="table-responsive">

                <table id="example" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>N° Référence</th>
                        <th>Client</th>
                        <th>Produits</th>
                        <th>Total <small>(fcfa)</small></th>
                        <th>Date</th>
                        <th>Statut</th>
                        <th>Livraison</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for order in orders %}
                    <tr>
                        <td><a href="{% url 'product:detailOrder' order.id %}" style="text-decoration: none;">{{ order.ref_code   }}</a></td>
                        <td>{{ order.user.fullname   }}</td>
                        <td>{{ order.produits.count   }}</td>
                        <td>{{ order.get_total }}</td>
                        <td>{{ order.ordered_date }}</td>
                        <td class="mx-auto pl-4">{% if order.ordered ==  False  %}<span class="badge badge-success"> En cours </span>{% else %}<span class="badge badge-success"> Terminé </span>{% endif %}</td>
                        <td class="mx-auto pl-4">{% if order.being_delivered ==  False  %}<span class="badge badge-success"> Non livré </span>{% elif order.being_delivered ==  True and order.received == False  %}<span class="badge badge-success"> En cours de livraison </span>{% elif order.being_delivered ==  True and order.received == True  %}<span class="badge badge-success"> Reçu </span>{% endif %}</td>
                        <td><!--a href="{% url 'product:editOrder' order.id %}" style="text-decoration: none;" class="text-success"><i class="fa fa-edit mx-2"--></i></a>
                            <a href="{% url 'product:deleteOrder' order.id %}" style="text-decoration: none;" class="text-primary px-2" data-toggle="modal" data-target="#centralModalWarning"><i class="fa fa-eye"></i></a>
                           
                         <!-- Central Modal Medium Warning -->
						 <div class="modal fade" id="centralModalWarning" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
						   <div class="modal-dialog modal-notify" role="document">
						     <!--Content-->
						     <div class="modal-content">
						       <!--Header-->
						       <div class="modal-header  bg-default">
						         <p class="heading lead">N° Commande: {{ order.ref_code   }}</p>
						
						         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
						           <span aria-hidden="true" class="white-text">&times;</span>
						         </button>
						       </div>
						
						       <!--Body-->
						       <div class="modal-body">
						         <div class="">
						           <!--i class="fas fa-check fa-4x mb-3 animated rotateIn"></i-->
						           <div class="row">
						           		<div class="col-md-6">
						           			<small>{{ order.user.firstname   }} {{ order.user.lastname   }}</small><br/>
								            <small>{{ order.shipping_address.twon }}</small><br/>
								            <small>{{ order.shipping_address.street_address }}</small><br/>
								            <small>Tel: {{ order.shipping_address.tel }}</small><br/>
						           		</div>
						           		<div class="col-md-6 float-right">
										    <a class="navbar-brand font-weight-bold" href="/"><strong>PROXI<span class="text-danger">Market</span></strong></a>
										</div>
						           </div><br/>
						           
						           <div class="table-wrapper-scroll-y my-custom-scrollbar text-center">

										  <table class="table table-bordered table-striped mb-0">
										    <thead>
										      <tr>
										        <th scope="col">#</th>
										        <th scope="col">Produit</th>
										        <th scope="col">Qté</th>
										        <th scope="col">Prix</th>
										        <th scope="col">Total</th>
										      </tr>
										    </thead>
										    <tbody>
										    	{% for p in order.get_items %}
												      <tr>
												        <th scope="row">1</th>
												        <td>Mark</td>
												        <td>2</td>
												        <td>5000</td>
												        <td>10000</td>
												      </tr>
										    	{% endfor %}
										    </tbody>
										  </table>
										  <br/>
										<strong>TOTAL: 50000 fcfa</strong>
								    </div>
						           
									<!-- Horizontal Steppers -->
									<div class="row">
									  <div class="col-md-12">
									
									    <!-- Stepers Wrapper -->
									    <ul class="stepper stepper-horizontal">
									
									      <!-- First Step -->
									      <li class="completed">
									        <a href="#!">
									          <span class="label"> - </span>
									        </a>
									      </li>
									
									      <!-- Second Step -->
									      <li class="active">
									        <a href="#!">
									          <span class="circle">0</span>
									          <span class="label">{{ order.status }}</span>
									        </a>
									      </li>
									
									      <!-- Third Step -->
									      <li class="active">
									        <a href="#!">
									          <span class="label"> - </span>
									        </a>
									      </li>
									
									    </ul>
									    <!-- /.Stepers Wrapper -->
									
									  </div>
									</div>
									<!-- /.Horizontal Steppers -->
						         </div>
						       </div>
						
						       <!--Footer-->
						       <div class="modal-footer justify-content-center">
						         <a type="button" class="btn btn-danger text-white" href="#">Imprimer la facture</a>
						         <a type="button" class="btn btn-default text-white" href="#">Traiter</a>
						       </div>
						     </div>
						     <!--/.Content-->
						   </div>
						 </div>
						 <!-- Central Modal Medium Warning-->
                         </td>
                    </tr>
                    
                    {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>


{% endblock %}


{% block script %}

<script src="{% static 'admin/js/jquery.dataTables.min.js' %}"></script>

<script src="{% static 'admin/js/dataTables.bootstrap4.min.js' %}"></script>
<script>


    $(document).ready(function() {
       $('#example').DataTable( {
    language: {
        processing:     "Traitement en cours...",
        search:         "Rechercher&nbsp;:",
        lengthMenu:     "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }
} );
    } );
</script>

<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
     },5000)

</script>

{% endblock %}