omar/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from omar.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('categorie/', include('categorie.urls')),
    path('product/', include('product.urls')),
    path('contact/', include('contact.urls')),
    path('back_office/', include('back_office.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import OrderSummaryView, navShopView, SellerView, order_list, order_create, order_delete, order_detail, \
    order_edit, add_to_cart, add_to_cart_quick, remove_from_cart, remove_single_produit_from_cart, CheckoutView, \
    AddCouponView

app_name = 'product'

urlpatterns = [

    path('liste', views.product_list, name='indexProduit'),
    path('create/', views.product_create, name='createProduit'),
    path('<int:product_id>/', views.product_detail, name='detailProduit'),
    path('detail/<int:product_id>/', views.view_product, name='viewProduit'),
    #path('edit/<int:product_id>/', views.product_edit, name='editProduit'),
    url(r'(?P<id>\d+)/product_edit/$', views.product_edit, name='editProduit'),
    path('delete/<int:product_id>/', views.product_delete, name='deleteProduit'),

    path('order-summary/', OrderSummaryView, name='order-summary'),
    path('shop/<str:slug>/', navShopView, name='shop'),
    path('seller/', SellerView.as_view(), name='seller'),

    # url Order

    path('order', order_list, name='indexOrder'),
    path('order/create/', order_create, name='createOrder'),
    path('order/<int:order_id>/', order_detail, name='detailOrder'),
    path('order/edit/<int:order_id>/', order_edit, name='editOrder'),
    path('order/delete/<int:order_id>/', order_delete, name='deleteOrder'),

    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('add-to-cart-quick/<pk>/', add_to_cart_quick, name='add-to-cart-quick'),

    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-produit-from-cart/<pk>/', remove_single_produit_from_cart,
         name='remove_single_produit_from_cart'),
    path('checkout/', CheckoutView, name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
]

product/models.py
from django.db import models
from categorie.models import Categorie
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django_countries.fields import CountryField
from .enum import *
from django.utils import timezone
from django.contrib import messages


# Create your models here.
from omar import settings


class Produit(models.Model):
    title = models.CharField("Nom du produit", max_length=250)
    code_ref = models.CharField(max_length=100, blank=True, null=True)
    price = models.FloatField('Prix')
    purchase_price = models.FloatField("Prix d'achat", blank=True, null=True)
    sale_price = models.FloatField(blank=True, null=True)
    discount_price = models.FloatField("Prix réduit", blank=True, null=True)
    categorie = models.ForeignKey(Categorie, on_delete=models.CASCADE, default=None, blank=True, null=True, related_name='produits')
    label = models.CharField("Label", choices=LABEL_CHOICES, max_length=1)
    description = models.TextField("Description")
    gender = models.CharField("Genre", choices=GENDER_CHOICES, max_length=1, default='X')
    color = models.CharField("Couleur",choices=COLOR_CHOICES, max_length=2, default='X')
    size_cloth = models.CharField("Taille", choices=CLOTH_SIZE_CHOICES, max_length=2, default='X')
    size_shoes = models.CharField("Pointure", choices=SHOES_SIZE_CHOICES, max_length=2, default='X')
    star = models.IntegerField(default=0)
    provider = models.CharField("Fournisseur", max_length=100, default='proximarket')
    stock = models.IntegerField(default=1)
    status = models.CharField("Statut", choices=STATUS_CHOICES, max_length=1, default='D')
    origin = models.CharField(choices=ORIGIN, max_length=2, default='X')
    marque = models.CharField(max_length=100, blank=True, null=True, default='Générique')
    agent = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None, null=True)


    def __str__(self):
        return self.title

# Create your models here.
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('product:detailProduit', args=[self.pk])

    def get_absolute_url(self):
        return reverse("product:product", kwargs={
            'pk': self.pk
        })


    def get_add_to_cart_url(self):
        return reverse("product:add-to-cart", kwargs={
            'pk': self.pk
        })

    def get_add_to_cart_quick_url(self):
        return reverse("product:add-to-cart-quick", kwargs={
            'pk': self.pk
        })

    def get_remove_from_cart_url(self):
        return reverse("product:remove-from-cart", kwargs={
            'pk': self.pk
        })






class Photos(models.Model):
    photo = models.ImageField(blank=True, null=True)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE, default=None, related_name='photos')

    def __str__(self):
        return self.id

class OrderProduit(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE, default=None)
    ordered = models.BooleanField(default=False)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    sessionID = models.CharField(max_length=200, default='X')

    def __str__(self):
        return f"{self.quantity} of {self.produit.title}"

    def get_total_produit_price(self):
        return self.quantity * self.produit.price

    def get_total_discount_produit_price(self):
        return self.quantity * self.produit.discount_price

    def get_amount_saved(self):
        return self.get_total_produit_price() - self.get_total_discount_produit_price()

    def get_final_price(self):
        if self.produit.discount_price:
            return self.get_total_discount_produit_price()
        return self.get_total_produit_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True, blank=True)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    produits = models.ManyToManyField(OrderProduit)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    payment_option = models.CharField(max_length=2, blank=True, null=True)
    sessionID = models.CharField(max_length=200, default='X', null=True)

    '''
    1. Produit added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.sessionID

    def get_total(self):
        total = 0
        for order_produit in self.produits.all():
            total += order_produit.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total


    def get_produits(self):
        print(self.produits.all())
        return self.produits.all()


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    town  = models.CharField(max_length=10, choices=TOWN, default="1")
    telephone = models.CharField(max_length=15, default="X")

    def __str__(self):
        return self.user.username



class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

product/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
from categorie.models import Categorie
from . import models
from .enum import *
from .models import Produit, Photos


class CreateProduit(forms.ModelForm):
    title = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Libellé du produit'}), required=False)
    categorie = forms.ModelChoiceField(label='Catégorie', queryset=Categorie.objects.all(), widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Genre'}))
    gender = forms.ChoiceField(label='Genre', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Genre'}), choices=GENDER_CHOICES)
    color = forms.ChoiceField(label='Couleur', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Couleur'}), choices = COLOR_CHOICES)
    price = forms.CharField(label="Prix", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prix d achat'}), required=False)
    purchase_price = forms.CharField(label="Prix de vente", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prix de vente'}), required=False)
    provider = forms.CharField(label="Fournisseur", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Fournisseur'}), required=False)
    size_cloth = forms.ChoiceField(label='Taille', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Taille'}),choices = CLOTH_SIZE_CHOICES)
    size_shoes = forms.ChoiceField(label='Pointure', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Pointure'}),choices = SHOES_SIZE_CHOICES)
    stock = forms.CharField(label="Stock", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Quantité'}), required=False)
    label = forms.ChoiceField(label='Label', widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Label'}),choices = LABEL_CHOICES)
    marque = forms.CharField(label="Marque", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Marque du produit'}))
    description = forms.CharField(label="Description", widget=forms.Textarea(attrs={"rows":5, "cols":20, 'class': 'form-control', 'placeholder': 'Caractéristiques du produit'}))

    class Meta:
        model = Produit
        fields = ['title','categorie', 'gender', 'color', 'price', 'purchase_price', 'provider', 'size_cloth', 'size_shoes', 'stock', 'label', 'marque', 'description']

class CreatePhoto(forms.ModelForm):
    class Meta:
        model = Photos
        fields = ['photo']


# Form de Order
class CreateOrder(forms.ModelForm):
    class Meta:
        model = models.Order
        fields = ['user', 'ref_code']




class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=True)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_town = forms.CharField(label="Test", widget=forms.Select(attrs={'class': 'form-control'}, choices=TOWN), required=True)

    shipping_tel = forms.CharField(required=True)
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(Pays)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)

class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo code',
        'aria-label': 'Recipient\'s username',
        'aria-describedby': 'basic-addon2'
    }))



class CreateAdresse(forms.ModelForm):
    street_address = forms.CharField(label="", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Libellé du produit'}), required=False)
    apartment_address = forms.CharField(label="Prix", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prix d achat'}), required=False)
    country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    zip = forms.CharField(label="Zip", widget=forms.Select(attrs={'class': 'form-control'}, choices=TOWN), required=True)
    address_type = forms.CharField(label="Type", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prix d achat'}), required=False)
    town = forms.CharField(label="Ville", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prix d achat'}), required=False)
    tel = forms.CharField(label="Téléphone", widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prix d achat'}), required=False)
    class Meta:
        model = models.Address
        fields = ['street_address', 'apartment_address', 'country', 'zip', 'address_type', 'town', 'tel']

product/templates/product/order_snippet.html
<div class="col-md-12">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Votre panier</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Code promo</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-{{ order.coupon.amount }} Fcfa</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (Fcfa)</span>
        <strong>{{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'product:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Racheter</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>

product/templates/product/product_create.html
{% extends 'base.html' %}
{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block content %}



{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}


<div class="container-fluid py-2">


    <!--Section: Content-->
    <section class="dark-grey-text">

        <!-- Section heading -->
        <h3 class="font-weight-bold text-center"></h3>
        <!-- Section description -->
        <p class="text-center w-responsive mx-auto pb-5 text-justify">

        </p>

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-lg-8 mx-auto">

                <!-- Form with header -->
                <div class="card">
                    <div class="card-body">
                        <!-- Header -->
                        <div class="form-header bg-default accent-1">
                            <h3 class="mt-2"><i class="fas fa-purchase"></i> Création produit </h3>
                        </div>
                        <!-- Body -->
        <form  action="{% url 'product:createProduit' %}"  method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}


            <div class="row">

                {% for field in form %}
                        {% if forloop.last %}
                        <div class="col-md-12">
                            <div class="md-form mb-0">
                                {{ field.errors }}
                                {{ field }}
                            </div>
                        </div>
                        {% elif forloop.counter0|divisibleby:"2" %}
                        <div class="col-md-6">
                                <div class="md-form mb-0">
                                    {{ field.errors }}
                                     {{ field }}
                                </div>
                        </div>
                        {% else %}
                        <div class="col-md-6">
                                <div class="md-form mb-0">
                                    {{ field.errors }}
                                    {{ field }}
                                </div>
                        </div>
                        {% endif %}
                {% endfor %}
            </div>
            <div class="row">
                {{ formset.management_form }}
                {% for f in formset %}
                    <div class="form-group">
                    {{ f }}
                    </div>
                {% endfor %}
            </div>

            <div class="row mt-1">
                <div class="col-md-12 text-right">
                    <a href="/" type="button" class="btn text-dark">Retour</a>
                    <input value="Enregistrer" class="btn btn-danger" type="submit"/>
                </div>
            </div>
        </form>



</div>

</div>

</div>

</div>


    </section>




{% endblock %}

product/templates/product/product_edit.html
{% extends 'base.html' %}
{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block content %}



{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}

<div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <h1 class="mt-2">Mis à jour produit</h1>
          <hr class="mt-0 mb-4">
		    <form method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ form.as_p }}
                {{ formset.management_form }}
                {% for f in formset %}
                  {{ f.as_p }}
                {% endfor %}


		      <input type="submit" value="Modifier le produit" class="btn btn-success float-right"/>
		    </form>
        </div>
      </div>
    </div>



{% endblock %}
  

product/templates/product/product_list.html
{% extends 'admin/base_admin.html' %}
{% load static %}
{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}

{% block footer %}
{% include 'admin/footer_admin.html' %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/dataTables.bootstrap4.min.css' %}"/>
{% endblock %}

{% block content %}
<div class="container pt-4 alertCustom">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
</div>
<div class="container py-2">

    <h2 align="center" class="customColor pt-2">Liste des produits</h2>



    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{% url 'product:createProduit' %}" class="btn bg-default float-right  text-white" type="button"> Ajouter un produit </a>
        </div>
        <div class="card-body">
            <div class="table-responsive">

                <table id="example" class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <th>Libellé</th>
                        <th>Référence</th>
                        <th>Prix de vente</th>
                        <th>Catégorie</th>
                        <th>Fournisseur</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for produit in produits %}
                    <tr>
                        <td><a href="{% url 'product:detailProduit' produit.id %}" style="text-decoration: none;" class="customColor">{{ produit.title   }}</a></td>
                        <td>{{ produit.code_ref   }}</td>
                        <td>{{ produit.price   }}</td>
                        <td>{{ produit.categorie }}</td>
                        <td>{{ produit.provider }}</td>
                        <td><a href="{% url 'product:editProduit' produit.id %}" style="text-decoration: none;" class="text-success" ><i class="fa fa-edit mx-2"></i></a>
                            <a href="{% url 'product:deleteProduit' produit.id %}" style="text-decoration: none;" class="text-danger" ><i class="fa fa-trash"></i></a></td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>




{% endblock %}


{% block script %}

<script src="{% static 'admin/js/jquery.dataTables.min.js' %}"></script>

<script src="{% static 'admin/js/dataTables.bootstrap4.min.js' %}"></script>
<script>


    $(document).ready(function() {
       $('#example').DataTable( {
    language: {
        processing:     "Traitement en cours...",
        search:         "Rechercher&nbsp;:",
        lengthMenu:     "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }
} );
    } );
</script>

<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
     },5000)

</script>

{% endblock %}

product/templates/product/shop.html
{% extends 'base.html' %}

{% block navbar %}
	{% include 'navbar.html' %}
{% endblock %}

{% block fullcontent %}

{% block megamenu %}
	{% include 'megamenu.html' %}
{% endblock %}

    <!-- Main Container -->
<div class="container pt-2">
	<section>
		    <div class="row">
		        <div class="col-lg-12">
		
		          <!-- Products grid-->
		          <div class="row mx-n2">
		            <!-- Product-->
				          {% for produit in products %}
				
				            <!--div class="col-md-3 col-sm-4 px-2 mb-4">
				              <div class="card product-card card-static">

						                <button class="btn-wishlist btn-sm" type="button" data-toggle="tooltip" data-placement="left" title="" data-original-title="Add to wishlist" style="color:red;">
						                    <i class="fa fa-heart"></i>
						                </button>

				                      <br/>
				                      <span class="badge badge-pill {{ produit.get_label_display }}-color">Nouveau</span>

					                    <a class="card-img-top d-block overflow-hidden py-2" href="{% url 'product:viewProduit' produit.id %}" style="height:250px; object-fit: cover">
						                      <img src="{{ produit.myphoto.photo.url }}" alt="Product" class="rounded img-fluid" style="height: 100%;">
					                    </a>

				                    <div class="card-body py-2">

				                              <a class="product-meta d-block font-size-xs pb-1" href="{% url 'product:viewProduit' produit.id %}">
				                              {{  produit.title }}
				                              </a>

				                            <h3 class="product-title font-size-sm">{{  produit.get_category_display }}</h3>
				                          <div class="d-flex justify-content-between">

				                          	<div class="product-price">
				                                  {% if produit.discount_price %}
				                                        <span class="text-accent">{{ produit.discount_price }}</span>
				                                  {% else %}
				                                        <span class="text-accent">{{ produit.price }} Fcfa</span>
				                                  {% endif %}
				                          	</div>

				                  		</div>
				                	</div>

				              </div>
				              <hr class="d-sm-none">
				            </div-->
							
							<div class="col-lg-3 col-md-6 mb-4">
	
	                            <div class="card card-ecommerce">
	
	                                <div class="view overlay">
	                                    <img src="{{ produit.photos.first.photo.url }}" class="img-fluid" alt="">
	                                    <a href="{% url 'product:viewProduit' produit.id %}">
	                                        <div class="mask rgba-white-slight"></div>
	                                    </a>
	                                </div>
	                                
	                                <div class="card-body">
	
	                                    <h5 class="card-title mb-1"><strong><a href="{% url 'product:viewProduit' produit.id %}" class="customColor">{{ produit.title }}</a></strong></h5><span class="badge badge-danger mb-2">bestseller</span>
	                                    
	                                    <div class="card-footer pb-0 customColor">
	                                        <div class="row mb-0">
	                                            <span class="float-left"><strong>{{ produit.price }} fcfa</strong></span>
	                                            <span class="float-right">
	
	                                                <a class="border-0 text-danger" data-toggle="tooltip" data-placement="top" title="Ajouter rapidement au panier" 
															href="{{ produit.get_add_to_cart_quick_url }}">
                                                        <i class="fas fa-shopping-cart ml-3"></i>
                                                    </a>
	                                            </span>
	                                        </div>
	                                    </div>
	
	                                </div>
	
	                            </div>
	
	                        </div>
								
				          {% endfor %}
		
		          		  <hr class="my-3">
		
		
		        	</div>
		       </div>
		    </div>
	</section>
</div>
{% endblock %}