accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    #path('signup/', views.signup_view, name='signup'),
    #path('login/', views.login_view, name='login'),
    #path('logout/', views.logout_view, name='logout'),
    
    
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('must_authenticate/', views.must_authenticate_view, name="must_authenticate"),
    path('register/', views.registration_view, name="register"),
    path('profile/', views.profile_view, name="profile"),

    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

contact/urls.py
from django.contrib import admin
from django.conf.urls import url
from . import views
from django.urls import path



app_name = 'contact'

urlpatterns = [
    path('', views.contact , name='contact'),
    path('listing', views.contact_list, name='indexContact'),
    path('<int:contact_id>/', views.contact_detail, name='detailContact'),
    path('delete/<int:contact_id>/', views.contact_delete, name='deleteContact'),
    path('treat/<int:contact_id>/', views.contact_treat, name='treatContact'),
    path('finish/<int:contact_id>/', views.contact_finish, name='finishContact'),

]

omar/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from omar.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('categorie/', include('categorie.urls')),
    path('product/', include('product.urls')),
    path('contact/', include('contact.urls')),
    path('back_office/', include('back_office.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import OrderSummaryView, navShopView, SellerView, order_list, order_create, order_delete, order_detail, \
    order_edit, add_to_cart, add_to_cart_quick, remove_from_cart, remove_single_produit_from_cart, CheckoutView, \
    AddCouponView

app_name = 'product'

urlpatterns = [

    path('liste', views.product_list, name='indexProduit'),
    path('create/', views.product_create, name='createProduit'),
    path('<int:product_id>/', views.product_detail, name='detailProduit'),
    path('detail/<int:product_id>/', views.view_product, name='viewProduit'),
    #path('edit/<int:product_id>/', views.product_edit, name='editProduit'),
    url(r'(?P<id>\d+)/product_edit/$', views.product_edit, name='editProduit'),
    path('delete/<int:product_id>/', views.product_delete, name='deleteProduit'),

    path('order-summary/', OrderSummaryView, name='order-summary'),
    path('shop/<str:slug>/', navShopView, name='shop'),
    path('seller/', SellerView.as_view(), name='seller'),

    # url Order

    path('order', order_list, name='indexOrder'),
    path('order/create/', order_create, name='createOrder'),
    path('order/<int:order_id>/', order_detail, name='detailOrder'),
    path('order/edit/<int:order_id>/', order_edit, name='editOrder'),
    path('order/delete/<int:order_id>/', order_delete, name='deleteOrder'),

    path('add-to-cart/<pk>/', add_to_cart, name='add-to-cart'),
    path('add-to-cart-quick/<pk>/', add_to_cart_quick, name='add-to-cart-quick'),

    path('remove-from-cart/<pk>/', remove_from_cart, name='remove-from-cart'),
    path('remove-produit-from-cart/<pk>/', remove_single_produit_from_cart,
         name='remove_single_produit_from_cart'),
    path('checkout/', CheckoutView, name='checkout'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Proximarket</title>

    <link rel="stylesheet"  href="{% static 'css/all.css' %}">
    <link rel="stylesheet"  href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet"  href="{% static 'css/mdb.css' %}">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="{% static 'css/mdb.admin.min.css' %}">
    <link rel="stylesheet"  href="{% static 'css/jquery-ui.css' %}" media="all">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">

    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/popper.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/mdb.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/js-cookie.js' %}"></script>

    <style>

    .sticky {
		  position: fixed;
		  top: 0;
		  right : 0;
		  left : 0;
		  width: 100%;
		  z-index:300;
		  transform: translateZ(0);
		  transition:all 0.5s;
	}

  </style>

</head>

<body>

{% block navbar %}
{% endblock %}

{% block content %}
{% endblock %}

{% block fullcontent %}
{% endblock %}

{% block extra_body %}
{% endblock %}

{% include "footer.html" %}
{% include "scripts.html" %}

{% block scripts %}
{% endblock %}

<!--Modal: modalCookie-->
<div class="modal fade bottom" id="modalCookie1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true" data-backdrop="true">
    <div class="modal-dialog modal-frame modal-top modal-notify modal-info" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Body-->
            <div class="modal-body">
                <div class="row d-flex justify-content-center align-items-center">

                    <p class="pt-3 pr-2">Ce site utilise des cookies afin d'améliorer l'expérience des visiteurs et leur proposer des publications adaptées à leur profil...</p>

                    <a type="button" class="btn text-dark">En savoir plus <i class="fa fa-plus ml-1"></i></a>
                    <a type="button" class="btn btn-outline-danger waves-effect customColor" data-dismiss="modal">Ok, Merci</a>
                </div>
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>
<!--Modal: modalCookie-->

</body>
</html>

templates/navbar-auth.html
{#% load cart_template_tags %#}
{% load static %}

<!--Navigation-->
    <header>
        
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg  navbar-light scrolling-navbar white">
            <div class="container">
            
                <div class="row">
                    <div class="col-md-6">
                		<a class="navbar-brand font-weight-bold float-right" href="/"><strong>PROXI<span class="text-danger">Market</span></strong></a>
                    </div>
                    <div class="col-md-6">
                    	<p>Toujours plus prés <br/> Toujours moins chér !</p>
                    </div>
                </div>
            </div>
        </nav>
        <!-- /.Navbar -->

    </header>
<!-- /.Navigation -->

{% block script %}

{% endblock %}

templates/navbar.html
{% load template_tags %}
{% load static %}

{% block navbar %}

<!--Navigation-->
    <header>
        
        <!-- Navbar -->
        <nav class="navbar fixed-top navbar-expand-lg  navbar-light scrolling-navbar white">
            <div class="container">
                <!-- SideNav slide-out button -->
                <!--div class="float-left mr-2">
                    <a href="#" data-activates="slide-out" class="button-collapse"><i class="fas fa-bars"></i></a>
                </div-->
                <a class="navbar-brand font-weight-bold" href="/"><strong>PROXI<span class="text-danger">Market</span></strong></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent-4" aria-controls="navbarSupportedContent-4"
                    aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent-4">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-produit dropdown ml-3">
                            
                            <a class="nav-link dropdown-toggle waves-effect waves-light dark-grey-text font-weight-bold" id="navbarDropdownCartLink-4" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                                <span class="badge danger-color">{#{ request|cart_produit_count }#}</span>
                                <i class="fas fa-shopping-cart customColor"></i> 
			                    Panier 
                           </a>
                            <div class="dropdown-menu dropdown-menu-right dropdown-cyan" aria-labelledby="navbarDropdownCartLink-4">

		                                    {% for order_produit in request %}
											
												<a class="dropdown-produit customOver" href="{{ order_produit.produit.get_absolute_url }}">
		
													<span class="d-block mr-2" style="width: 64px; height: 64px">
		                                                <img style="width: 100%;height: 100%;" src="{{ order_produit.produit.image.url }}" alt="Product"/>
		                                            </span>
												
		                                            <span class="widget-product-title">{{ order_produit.produit.title }}</span>
		                                            <span class="text-accent mr-2">
		                                                  {% if produit.discount_price %}
		                                                        <span style="color: #ad251c;">{{ order_produit.produit.discount_price }}</span>
		                                                  {% else %}
		                                                        <span style="color: #ad251c;">{{ order_produit.produit.price }} Fcfa</span>
		                                                  {% endif %}
		                                            </span>
		                                            <span class="text-muted">x{{ order_produit.quantity }}</span>
		                                            
		                                            <span>
				                                        <a class="close text-danger" type="button" aria-label="Remove" href="{% url 'product:remove_single_item_from_cart' order_produit.produit.pk %}">
				                                            <span aria-hidden="true"><i class="fas fa-trash float-right"></i></span>
				                                        </a>
			                                        </span>
												</a>
		                                    
		                                    {% endfor %}
	                                    
											
		                                    <a class="dropdown-produit customOver">
		                                        <span class="text-muted">Total:</span>
		                                        <span class="text-accent font-size-base ml-1">{{ request|cart_total }}</span>
		                                    </a>
										
										
	                                    <a class="btn btn-outline-secondary btn-sm" href="{% url 'product:order-summary' %}">Agrandir le panier <i class='fas fa-arrow-right'></i></a>
	                              
	                        </div>
                                
                        </li>
                        <li class="nav-produit">
                            <a class="nav-link waves-effect waves-light dark-grey-text font-weight-bold" href="{% url 'contact:contact' %}"><i class="fas fa-envelope customColor"></i> Contact</a>
                        </li>
                        <li class="nav-produit dropdown ml-3">
                            <a class="nav-link dropdown-toggle waves-effect waves-light dark-grey-text font-weight-bold" id="navbarDropdownMenuLink-4" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false"><i class="fas fa-user customColor"></i> Compte </a>
                            <div class="dropdown-menu dropdown-menu-right dropdown-cyan" aria-labelledby="navbarDropdownMenuLink-4">
                                {% if request.user.is_authenticated %}
                                <a class="dropdown-produit customOver" href="{% url 'accounts:profile' %}">Mon compte</a>
                                <!--a class="dropdown-produit customOver" href="#">Mes historiques</a-->
			                   	<a class="dropdown-produit customOver" href="{% url 'accounts:logout' %}">Déconnexion</a>
			                    {% else %}
								<a class="dropdown-produit customOver" href="{% url 'accounts:login' %}">Connexion</a>
			                    {% endif %}
                            </div>
                        </li>
                    </ul>
                    
                    
                </div>
            </div>
        </nav>
        <!-- /.Navbar -->

    </header>
<!-- /.Navigation -->

{% endblock %}

templates/scripts.html
{% load static %}
  
<!-- <script type="text/javascript" src="{% static 'old/js/jquery-3.3.1.min.js' %}"></script>

<script type="text/javascript" src="{% static 'old/js/popper.min.js' %}"></script>

<script type="text/javascript" src="{% static 'old/js/bootstrap.min.js' %}"></script>

<script type="text/javascript" src="{% static 'old/js/mdb.min.js' %}"></script> -->

<script type="text/javascript">
  // Animations initialization
  new WOW().init();

</script>
<!-- <script src="{% static 'old/js/vendor.min.js' %}"></script>
<script src="{% static 'old/js/theme.min.js' %}"></script> -->