categorie/urls.py
from django.urls import path
from . import views

app_name = 'categorie'

urlpatterns = [
    path('', views.categorie_list, name='indexCategorie'),
    path('create/', views.categorie_create, name='createCategorie'),
    path('<int:categorie_id>/', views.categorie_detail, name='detailCategorie'),
    path('edit/<int:categorie_id>/', views.categorie_edit, name='editCategorie'),
    path('delete/<int:categorie_id>/', views.categorie_delete, name='deleteCategorie'),
]

omar/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from omar.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls')),
    path('categorie/', include('categorie.urls')),
    path('product/', include('product.urls')),
    path('contact/', include('contact.urls')),
    path('back_office/', include('back_office.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

categorie/models.py
from django.db import models


# Create your models here.

class Categorie(models.Model):
    nom = models.CharField(max_length=100, unique=True)
    update = models.DateTimeField(auto_now_add=True)
    is_sale  = models.BooleanField(default=True)
    is_actif  = models.BooleanField(default=True)

    def __str__(self):
        return self.nom

    def get_produits(self):
        return self.produits.all()

categorie/forms.py
from django import forms
from . import models

class CreateCategorie(forms.ModelForm):
    class Meta:
        model = models.Categorie
        fields = ['nom']

categorie/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import Http404
from .models import Categorie
from . import forms
from datetime import datetime, date
from django.contrib import messages



# Create your views here.

def categorie_list(request):
    classe_active = 'categorie'
    categories = Categorie.objects.all()

    return render(request, "categorie/categorie_list.html", locals())

def categorie_create(request):
    classe_active = 'categorie'
    if request.method == 'POST':
        form = forms.CreateCategorie(request.POST, request.FILES)
        if form.is_valid():
            # save article to DB # DEBUG: # TODO:
            form.save()
            messages.success(request, "Le catégorie a été créee avec succès !")
            return redirect('categorie:indexCategorie')
    else:
        form = forms.CreateCategorie()
    return render(request, 'categorie/categorie_create.html', {'form': form, 'classe_active': classe_active})


def categorie_detail(request, categorie_id):
	try:
		categorie = Categorie.objects.get(pk=categorie_id)
	except Categorie.DoesNotExist:
		raise Http404("Le categorie n'existe pas")
	return render(request, 'categorie/categorie_detail.html', locals())


def categorie_edit(request, categorie_id):
    classe_active = 'categorie'
    post = get_object_or_404(Categorie, pk=categorie_id)
    if request.method == 'POST':
        form = forms.CreateCategorie(request.POST, request.FILES, instance=post)
        if form.is_valid():
            # save categorie to DB # DEBUG: # TODO:
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            messages.success(request, "Le catégorie a été modifiée avec succès !")
            return redirect('categorie:indexCategorie')
    else:
        form = forms.CreateCategorie(instance=post)
        
    return render(request, 'categorie/categorie_create.html', {'form': form, 'classe_active': classe_active})


def categorie_delete(request, categorie_id):

    categorie= Categorie.objects.filter(pk=categorie_id)
    categorie.delete()
    messages.success(request, "Le catégorie a été supprimée avec succès !")
    categories = Categorie.objects.all()

    return redirect('categorie:indexCategorie')

categorie/templates/categorie/categorie_create.html
{% extends 'admin/base_admin.html' %}
{% block titre %} {{ block.super }} - Catégorie {% endblock %}

{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}

{% block footer %}
{% include 'admin/footer_admin.html' %}
{% endblock %}
{% block content %}

<div class="container-fluid py-2">


    <!--Section: Content-->
    <section class="dark-grey-text">

        <!-- Section heading -->
        <h3 class="font-weight-bold text-center"></h3>
        <!-- Section description -->
        <p class="text-center w-responsive mx-auto pb-5 text-justify">

        </p>

        <!-- Grid row -->
        <div class="row">

            <!-- Grid column -->
            <div class="col-lg-8 mx-auto">

                <!-- Form with header -->
                <div class="card">
                    <div class="card-body">
                        <!-- Header -->
                        <div class="form-header bg-default accent-1">
                            <h3 class="mt-2"><i class="fas fa-purchase"></i> Création categorie </h3>
                        </div>
                        <!-- Body -->

                        <form id="product-form" name="product-form" action="."  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            <div class="text-center mx-auto">
                                {% if form.subject.errors %}
                                <ol role="">
                                    {% for error in form.subject.errors %}
                                    <li role="alert"><strong>{{ error|escape }}</strong></li>
                                    {% endfor %}
                                </ol>
                                {% endif %}
                            </div>

                            <!-- Vertical Steppers -->
                            <div class="row">
                                <div class="col-md-12">

                                    <!-- Stepers Wrapper -->
                                    <ul class="stepper stepper-vertical">
                                        <div class="md-form mb-0">



                                            <!-- Section Description -->
                                            <div class="step-content w-100 px-4 mx-auto white lighten-3 row">
                                                {% for field in form %}
                                                {{ field }}
                                                {% endfor %}

                                            </div>
                                        </div>


                                    </ul>
                                    <!-- /.Stepers Wrapper -->

                                </div>
                            </div>

                            <!-- Steppers Navigation -->
                            <div class="row mt-1">
                                <div class="col-md-12 text-right">
                                    <a href="/" type="button" class="btn text-dark">Retour</a>
                                    <button class="btn btn-danger" type="submit">Enregistrer</button>
                                </div>
                            </div>
                            <!-- /.Vertical Steppers -->

                        </form>
                    </div>

                </div>

                <!-- Form with header -->

            </div>

        </div>
        <!-- Grid row -->

    </section>
    <!--Section: Content-->


</div>




{% endblock %}

categorie/templates/categorie/categorie_detail.html
{% extends 'base_admin.html' %}
{% block titre %} {{ block.super }} - Categorie {% endblock %}
{% block fullcontent %}

<div class="container">
<h2 align="center">Detail Categorie</h2>
    <div class="row">


            <div class="col-md-2">

            </div>

        <div class="col-md-7">
            <div  class="tab-content">


                <!-- Profile Image -->
                <div class="card card-primary card-outline">
                    <div class="card-body box-profile">


                        <h3 class="profile-username text-center">{{ categorie  }}</h3>

                        <p class="text-muted text-center"></p>

                        <ul class="list-group list-group-unbordered mb-3">
                            <li class="list-group-item">
                                <b>Intitulé</b> <a class="float-right">{{ categorie.nom }}</a>
                            </li>
                        </ul>

                        <a href="#" class="btn btn-primary btn-block"><b></b></a>
                        <a href="{% url 'categorie:editCategorie' categorie.id %}" style="text-decoration: none;" ><i class="fa fa-edit" style="font-size:24px"></i></a>
                        <a href="{% url 'categorie:deleteCategorie' categorie.id %}" style="text-decoration: none" onclick="return confirm('Voulez-vous vraiment supprimer l''gence {{ categorie.title }} ?');"><i class="fa fa-trash" style="font-size:24px"></i></a>

                    </div>
                </div>

             </div>


         </div>




      </div>
</div>







{% endblock %}

categorie/templates/categorie/categorie_list.html
{% extends 'admin/base_admin.html' %}
{% load static %}
{% block navbar %}
{% include 'admin/navbar_admin.html' %}
{% endblock %}


{% block sidebar %}
{% include 'admin/sidebar_admin.html' %}
{% endblock %}

{% block footer %}
{% include 'admin/footer_admin.html' %}
{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'admin/css/dataTables.bootstrap4.min.css' %}"/>
{% endblock %}

{% block content %}
<div class="container pt-4 alertCustom">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    {% endif %}
</div>
<div class="container py-2">

    <h2 align="center" class="customColor pt-2">Liste des carégories</h2>

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <a href="{% url 'categorie:createCategorie' %}" class="btn btn-success float-right pl-2" style="text-decoration: none;"> Ajouter une catégorie </a><br/>
        </div>

        <div class="card-body">
            <div class="table-responsive">

                <table id="example" class="table table-striped table-bordered" style="width:100%">
                    <thead>
                    <tr>
                        <th>Nom</th>
                        <th>Date de création</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>

                    {% for categorie in categories %}
                    <tr>
                        <td><a href="{% url 'categorie:detailCategorie' categorie.id %}" style="text-decoration: none;">{{ categorie   }}</a></td>
                        <td>{{ categorie.update | date:"d/m/Y" }}</td>
                        <td><a href="{% url 'categorie:editCategorie' categorie.id %}" style="text-decoration: none;" ><i class="fa fa-edit" style="font-size:24px"></i></a>
                            <a href="{% url 'categorie:deleteCategorie' categorie.id %}" style="text-decoration: none" onclick="return confirm('Voulez-vous vraiment supprimer l''gence {{ categorie.title }} ?');"><i class="fa fa-trash" style="font-size:24px"></i></a>
                        </td>
                    </tr>
                    {% endfor %}

                    </tbody>
                </table>

            </div>
        </div>
    </div>
</div>




{% endblock %}


{% block script %}
<script src="{% static 'vendor/js/jquery.dataTables.min.js' %}"></script>

<script src="{% static 'vendor/js/dataTables.bootstrap4.min.js' %}"></script>
<script>


    $(document).ready(function() {
       $('#example').DataTable( {
    language: {
        processing:     "Traitement en cours...",
        search:         "Rechercher&nbsp;:",
        lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
        info:           "Affichage de _START_ &agrave; _END_ sur _TOTAL_ &eacute;l&eacute;ments",
        infoEmpty:      "Affichage de 0 &agrave; 0 sur 0 &eacute;l&eacute;ments",
        infoFiltered:   "(filtr&eacute; de _MAX_ &eacute;l&eacute;ments au total)",
        infoPostFix:    "",
        loadingRecords: "Chargement en cours...",
        zeroRecords:    "Aucun &eacute;l&eacute;ment &agrave; afficher",
        emptyTable:     "Aucune donnée disponible dans le tableau",
        paginate: {
            first:      "Premier",
            previous:   "Pr&eacute;c&eacute;dent",
            next:       "Suivant",
            last:       "Dernier"
        },
        aria: {
            sortAscending:  ": activer pour trier la colonne par ordre croissant",
            sortDescending: ": activer pour trier la colonne par ordre décroissant"
        }
    }
} );
    } );
</script>



{% endblock %}